### ISSUE TITLE
Germany VAT is now 19%

### ISSUE THREAD

**Issue by firstpromoter** [VvanGemert/europe#1]
.The link used to update the rates doesn't have the correct values.
https://europa.eu/youreurope/business/taxation/vat/vat-rules-rates/index_en.htm

**Comment by VvanGemert** [comment]
Nice, an out-of-date EU official website. I will fix this asap. Thank you very much for letting me know @firstpromoter !

**Comment by VvanGemert** [comment]
It is fixed in v0.0.16. 
The repo is located at: 
https://github.com/gem-shards/europe.rb
https://rubygems.org/gems/europe
